-- World-class LMS Phase 8: evaluator-quality operations, credentials, governed evidence and cohort benchmarking.
-- MySQL 8.x; forward-only, trigger-free and compatible with Prisma Migrate.

CREATE TABLE IF NOT EXISTS evaluator_authorization_certificate (
  certificate_id CHAR(36) NOT NULL,
  certificate_code VARCHAR(64) NOT NULL,
  authorization_id CHAR(36) NOT NULL,
  evaluator_id VARCHAR(120) NOT NULL,
  evaluator_type VARCHAR(30) NOT NULL,
  template_id CHAR(36) NOT NULL,
  program_id CHAR(36) NOT NULL,
  calibration_assignment_id CHAR(36) NULL,
  issued_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  valid_from DATETIME(3) NOT NULL,
  valid_until DATETIME(3) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  verification_hash CHAR(64) NOT NULL,
  snapshot_json JSON NOT NULL,
  issued_by VARCHAR(120) NOT NULL,
  revoked_by VARCHAR(120) NULL,
  revoked_at DATETIME(3) NULL,
  revocation_reason LONGTEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (certificate_id),
  UNIQUE KEY uq_evaluator_certificate_code (certificate_code),
  UNIQUE KEY uq_evaluator_certificate_authorization (authorization_id),
  UNIQUE KEY uq_evaluator_certificate_hash (verification_hash),
  KEY idx_evaluator_certificate_owner (evaluator_id, evaluator_type, status, valid_until),
  KEY idx_evaluator_certificate_template (template_id, status, valid_until),
  CONSTRAINT fk_evaluator_certificate_authorization FOREIGN KEY (authorization_id)
    REFERENCES evaluator_authorization(authorization_id) ON DELETE RESTRICT,
  CONSTRAINT fk_evaluator_certificate_template FOREIGN KEY (template_id)
    REFERENCES practical_assessment_template(template_id) ON DELETE RESTRICT,
  CONSTRAINT fk_evaluator_certificate_program FOREIGN KEY (program_id)
    REFERENCES evaluator_calibration_program(program_id) ON DELETE RESTRICT,
  CONSTRAINT fk_evaluator_certificate_assignment FOREIGN KEY (calibration_assignment_id)
    REFERENCES evaluator_calibration_assignment(assignment_id) ON DELETE SET NULL,
  CONSTRAINT chk_evaluator_certificate_type CHECK (evaluator_type IN ('coordinator','admin','management')),
  CONSTRAINT chk_evaluator_certificate_status CHECK (status IN ('ACTIVE','SUSPENDED','EXPIRED','REVOKED')),
  CONSTRAINT chk_evaluator_certificate_validity CHECK (valid_until >= valid_from),
  CONSTRAINT chk_evaluator_certificate_hash CHECK (CHAR_LENGTH(verification_hash) = 64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS evaluator_calibration_anchor_evidence (
  evidence_id CHAR(36) NOT NULL,
  anchor_id CHAR(36) NOT NULL,
  evidence_code VARCHAR(100) NOT NULL,
  evidence_title VARCHAR(220) NOT NULL,
  evidence_type VARCHAR(30) NOT NULL,
  source_url TEXT NULL,
  storage_reference VARCHAR(500) NULL,
  text_content LONGTEXT NULL,
  content_hash CHAR(64) NULL,
  mime_type VARCHAR(160) NULL,
  file_size_bytes BIGINT UNSIGNED NULL,
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  visibility VARCHAR(40) NOT NULL DEFAULT 'EVALUATOR',
  retention_until DATETIME(3) NULL,
  approved_by VARCHAR(120) NULL,
  approved_at DATETIME(3) NULL,
  retired_by VARCHAR(120) NULL,
  retired_at DATETIME(3) NULL,
  retirement_reason LONGTEXT NULL,
  created_by VARCHAR(120) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (evidence_id),
  UNIQUE KEY uq_calibration_anchor_evidence_version (anchor_id, evidence_code, version_no),
  KEY idx_calibration_anchor_evidence_status (anchor_id, status, visibility),
  KEY idx_calibration_anchor_evidence_retention (status, retention_until),
  CONSTRAINT fk_calibration_anchor_evidence_anchor FOREIGN KEY (anchor_id)
    REFERENCES evaluator_calibration_anchor(anchor_id) ON DELETE CASCADE,
  CONSTRAINT chk_calibration_anchor_evidence_type CHECK (evidence_type IN ('DOCUMENT','IMAGE','VIDEO','AUDIO','LINK','TEXT','DATASET')),
  CONSTRAINT chk_calibration_anchor_evidence_status CHECK (status IN ('DRAFT','APPROVED','RETIRED')),
  CONSTRAINT chk_calibration_anchor_evidence_visibility CHECK (visibility IN ('EVALUATOR','AFTER_SUBMISSION','ADMIN_ONLY')),
  CONSTRAINT chk_calibration_anchor_evidence_size CHECK (file_size_bytes IS NULL OR file_size_bytes <= 10737418240),
  CONSTRAINT chk_calibration_anchor_evidence_source CHECK (source_url IS NOT NULL OR storage_reference IS NOT NULL OR text_content IS NOT NULL),
  CONSTRAINT chk_calibration_anchor_evidence_hash CHECK (content_hash IS NULL OR CHAR_LENGTH(content_hash) = 64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS evaluator_reliability_cohort_snapshot (
  cohort_snapshot_id CHAR(36) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  template_id CHAR(36) NOT NULL,
  cohort_type VARCHAR(20) NOT NULL,
  cohort_value VARCHAR(120) NOT NULL,
  evaluator_count INT UNSIGNED NOT NULL DEFAULT 0,
  evaluation_count INT UNSIGNED NOT NULL DEFAULT 0,
  paired_evaluation_count INT UNSIGNED NOT NULL DEFAULT 0,
  average_score_pct DECIMAL(6,2) NULL,
  average_agreement_pct DECIMAL(6,2) NULL,
  average_critical_agreement_pct DECIMAL(6,2) NULL,
  average_moderation_rate_pct DECIMAL(6,2) NULL,
  average_absolute_severity_index DECIMAL(8,2) NULL,
  reliable_count INT UNSIGNED NOT NULL DEFAULT 0,
  watch_count INT UNSIGNED NOT NULL DEFAULT 0,
  recalibration_required_count INT UNSIGNED NOT NULL DEFAULT 0,
  insufficient_data_count INT UNSIGNED NOT NULL DEFAULT 0,
  calculated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  calculated_by VARCHAR(120) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (cohort_snapshot_id),
  UNIQUE KEY uq_evaluator_cohort_period (period_start, period_end, template_id, cohort_type, cohort_value),
  KEY idx_evaluator_cohort_scope (cohort_type, cohort_value, period_end),
  KEY idx_evaluator_cohort_template (template_id, period_end),
  CONSTRAINT fk_evaluator_cohort_template FOREIGN KEY (template_id)
    REFERENCES practical_assessment_template(template_id) ON DELETE RESTRICT,
  CONSTRAINT chk_evaluator_cohort_period CHECK (period_end >= period_start),
  CONSTRAINT chk_evaluator_cohort_type CHECK (cohort_type IN ('COMPANY','BRANCH','PROCESS','LOB')),
  CONSTRAINT chk_evaluator_cohort_score CHECK (average_score_pct IS NULL OR average_score_pct BETWEEN 0 AND 100),
  CONSTRAINT chk_evaluator_cohort_agreement CHECK (average_agreement_pct IS NULL OR average_agreement_pct BETWEEN 0 AND 100),
  CONSTRAINT chk_evaluator_cohort_critical CHECK (average_critical_agreement_pct IS NULL OR average_critical_agreement_pct BETWEEN 0 AND 100),
  CONSTRAINT chk_evaluator_cohort_moderation CHECK (average_moderation_rate_pct IS NULL OR average_moderation_rate_pct BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO notification_template
  (template_id, template_code, event_type, channel, locale,
   subject_template, body_text_template, body_html_template,
   action_url_template, mandatory, version_no, active, created_by)
VALUES
  (UUID(), 'CALIBRATION_ASSIGNED_INAPP_V1', 'CALIBRATION_ASSIGNED', 'IN_APP', 'en-IN',
   'Evaluator calibration assigned',
   '{{programName}} has been assigned. Attempt {{attemptNo}} is due {{dueAt}}.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'CALIBRATION_ASSIGNED_EMAIL_V1', 'CALIBRATION_ASSIGNED', 'EMAIL', 'en-IN',
   'Evaluator calibration assigned: {{programName}}',
   'Hi {{recipientName}}, {{programName}} for {{templateName}} version {{templateVersion}} has been assigned. Attempt {{attemptNo}} is due {{dueAt}}.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p><b>{{programName}}</b> for <b>{{templateName}}</b> version {{templateVersion}} has been assigned.</p><p>Attempt {{attemptNo}} is due <b>{{dueAt}}</b>.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),

  (UUID(), 'CALIBRATION_DUE_INAPP_V1', 'CALIBRATION_DUE_REMINDER', 'IN_APP', 'en-IN',
   'Evaluator calibration due soon',
   '{{programName}} is due in {{daysRemaining}} day(s). Complete all anchor cases before {{dueAt}}.',
   NULL, '/evaluator-quality?role={{recipientType}}', 0, 1, 1, 'migration'),
  (UUID(), 'CALIBRATION_DUE_EMAIL_V1', 'CALIBRATION_DUE_REMINDER', 'EMAIL', 'en-IN',
   'Reminder: evaluator calibration due in {{daysRemaining}} day(s)',
   'Hi {{recipientName}}, {{programName}} is due {{dueAt}}. Complete and submit all anchor cases to maintain evaluation eligibility.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p><b>{{programName}}</b> is due <b>{{dueAt}}</b>.</p><p>Complete and submit all anchor cases to maintain evaluation eligibility.</p>',
   '/evaluator-quality?role={{recipientType}}', 0, 1, 1, 'migration'),

  (UUID(), 'CALIBRATION_OVERDUE_INAPP_V1', 'CALIBRATION_OVERDUE', 'IN_APP', 'en-IN',
   'Evaluator calibration overdue',
   '{{programName}} is overdue by {{overdueDays}} day(s). Complete it before accepting new evaluations.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'CALIBRATION_OVERDUE_EMAIL_V1', 'CALIBRATION_OVERDUE', 'EMAIL', 'en-IN',
   'Overdue evaluator calibration: {{programName}}',
   '{{programName}} is overdue by {{overdueDays}} day(s). Complete it immediately or contact the LMS administrator.',
   '<p><b>{{programName}}</b> is overdue by <b>{{overdueDays}} day(s)</b>.</p><p>Complete it immediately or contact the LMS administrator.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),

  (UUID(), 'AUTHORIZATION_EXPIRING_INAPP_V1', 'EVALUATOR_AUTHORIZATION_EXPIRING', 'IN_APP', 'en-IN',
   'Evaluator authorization expires soon',
   'Your {{templateName}} authorization expires in {{daysRemaining}} day(s) on {{validUntil}}.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'AUTHORIZATION_EXPIRING_EMAIL_V1', 'EVALUATOR_AUTHORIZATION_EXPIRING', 'EMAIL', 'en-IN',
   'Evaluator authorization expires in {{daysRemaining}} day(s)',
   'Hi {{recipientName}}, your authorization for {{templateName}} version {{templateVersion}} expires on {{validUntil}}. Complete any assigned recalibration before expiry.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p>Your authorization for <b>{{templateName}}</b> version {{templateVersion}} expires on <b>{{validUntil}}</b>.</p><p>Complete any assigned recalibration before expiry.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),

  (UUID(), 'AUTHORIZATION_EXPIRED_INAPP_V1', 'EVALUATOR_AUTHORIZATION_EXPIRED', 'IN_APP', 'en-IN',
   'Evaluator authorization expired',
   'Your {{templateName}} authorization expired on {{validUntil}}. Evaluation access is paused until renewal.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'AUTHORIZATION_EXPIRED_EMAIL_V1', 'EVALUATOR_AUTHORIZATION_EXPIRED', 'EMAIL', 'en-IN',
   'Evaluator authorization expired: {{templateName}}',
   'Your authorization for {{templateName}} version {{templateVersion}} expired on {{validUntil}}. Complete the current calibration programme to renew access.',
   '<p>Your authorization for <b>{{templateName}}</b> version {{templateVersion}} expired on <b>{{validUntil}}</b>.</p><p>Complete the current calibration programme to renew access.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),

  (UUID(), 'RELIABILITY_WATCH_INAPP_V1', 'EVALUATOR_RELIABILITY_WATCH', 'IN_APP', 'en-IN',
   'Evaluator reliability requires monitoring',
   '{{templateName}} reliability is in WATCH status. Agreement: {{agreementPct}}%; severity index: {{severityIndex}}.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'RELIABILITY_WATCH_EMAIL_V1', 'EVALUATOR_RELIABILITY_WATCH', 'EMAIL', 'en-IN',
   'Evaluator reliability watch: {{templateName}}',
   'Your {{templateName}} reliability is in WATCH status for {{periodStart}} to {{periodEnd}}. Review the assigned quality actions in MCN LMS.',
   '<p>Your <b>{{templateName}}</b> reliability is in <b>WATCH</b> status for {{periodStart}} to {{periodEnd}}.</p><p>Review the assigned quality actions in MCN LMS.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),

  (UUID(), 'RECALIBRATION_REQUIRED_INAPP_V1', 'EVALUATOR_RECALIBRATION_REQUIRED', 'IN_APP', 'en-IN',
   'Evaluator recalibration required',
   '{{templateName}} reliability requires recalibration. Complete the assigned action by {{dueAt}}.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'RECALIBRATION_REQUIRED_EMAIL_V1', 'EVALUATOR_RECALIBRATION_REQUIRED', 'EMAIL', 'en-IN',
   'Action required: evaluator recalibration',
   'Your {{templateName}} reliability requires recalibration. Complete the assigned action by {{dueAt}} before further evaluator authorization review.',
   '<p>Your <b>{{templateName}}</b> reliability requires <b>recalibration</b>.</p><p>Complete the assigned action by <b>{{dueAt}}</b>.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),

  (UUID(), 'CERTIFICATE_ISSUED_INAPP_V1', 'EVALUATOR_CERTIFICATE_ISSUED', 'IN_APP', 'en-IN',
   'Evaluator authorization certificate issued',
   'Certificate {{certificateCode}} has been issued for {{templateName}} and is valid until {{validUntil}}.',
   NULL, '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration'),
  (UUID(), 'CERTIFICATE_ISSUED_EMAIL_V1', 'EVALUATOR_CERTIFICATE_ISSUED', 'EMAIL', 'en-IN',
   'Evaluator certificate issued: {{templateName}}',
   'Hi {{recipientName}}, certificate {{certificateCode}} confirms your authorization for {{templateName}} version {{templateVersion}} until {{validUntil}}.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p>Certificate <b>{{certificateCode}}</b> confirms your authorization for <b>{{templateName}}</b> version {{templateVersion}} until <b>{{validUntil}}</b>.</p>',
   '/evaluator-quality?role={{recipientType}}', 1, 1, 1, 'migration');