-- Phase 6 supplement: practical-assessment notifications through the Phase 5 outbox.

INSERT IGNORE INTO notification_template
  (template_id, template_code, event_type, channel, locale,
   subject_template, body_text_template, body_html_template,
   action_url_template, mandatory, version_no, active, created_by)
VALUES
  (UUID(), 'PRACTICAL_ASSIGNED_INAPP_V1', 'PRACTICAL_ASSIGNED', 'IN_APP', 'en-IN',
   'Practical assessment assigned',
   '{{templateName}} has been assigned. Attempt {{attemptNo}} is due {{dueAt}}.',
   NULL, '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_ASSIGNED_EMAIL_V1', 'PRACTICAL_ASSIGNED', 'EMAIL', 'en-IN',
   'Practical assessment assigned: {{templateName}}',
   'Hi {{recipientName}}, {{templateName}} (version {{versionNo}}) has been assigned. Attempt {{attemptNo}} is due {{dueAt}}. Open MCN LMS to review the rubric and submit evidence.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p><b>{{templateName}}</b> (version {{versionNo}}) has been assigned.</p><p>Attempt {{attemptNo}} is due <b>{{dueAt}}</b>. Open MCN LMS to review the rubric and submit evidence.</p><p style="color:#667085;font-size:12px">MCN LMS · Practical Assessment</p>',
   '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_ASSIGNED_SMS_V1', 'PRACTICAL_ASSIGNED', 'SMS', 'en-IN',
   NULL,
   'MCN LMS: Practical assessment {{templateName}} assigned. Attempt {{attemptNo}} due {{dueAt}}. Open LMS for the rubric.',
   NULL, '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),

  (UUID(), 'PRACTICAL_SUBMITTED_INAPP_V1', 'PRACTICAL_SUBMITTED', 'IN_APP', 'en-IN',
   'Practical submission awaiting evaluation',
   '{{traineeName}} submitted {{templateName}} for independent evaluation.',
   NULL, '/practical-assessments?role=coordinator', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_SUBMITTED_EMAIL_V1', 'PRACTICAL_SUBMITTED', 'EMAIL', 'en-IN',
   'Evaluation required: {{traineeName}} · {{templateName}}',
   '{{traineeName}} ({{employeeId}}) submitted {{templateName}}. Claim an evaluator slot and complete the rubric review.',
   '<p><b>{{traineeName}}</b> ({{employeeId}}) submitted <b>{{templateName}}</b>.</p><p>Claim an evaluator slot and complete the rubric review in MCN LMS.</p><p style="color:#667085;font-size:12px">Batch {{batchNo}}</p>',
   '/practical-assessments?role=coordinator', 1, 1, 1, 'migration'),

  (UUID(), 'PRACTICAL_DUE_INAPP_V1', 'PRACTICAL_DUE_REMINDER', 'IN_APP', 'en-IN',
   'Practical assessment due soon',
   '{{templateName}} is due in {{daysRemaining}} day(s). Submit evidence before {{dueAt}}.',
   NULL, '/practical-assessments?role=trainee', 0, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_DUE_EMAIL_V1', 'PRACTICAL_DUE_REMINDER', 'EMAIL', 'en-IN',
   'Reminder: {{templateName}} due in {{daysRemaining}} day(s)',
   'Hi {{recipientName}}, your practical assessment {{templateName}} is due {{dueAt}}. Submit the required statement and evidence before the deadline.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p>Your practical assessment <b>{{templateName}}</b> is due <b>{{dueAt}}</b>.</p><p>Submit the required statement and evidence before the deadline.</p>',
   '/practical-assessments?role=trainee', 0, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_DUE_SMS_V1', 'PRACTICAL_DUE_REMINDER', 'SMS', 'en-IN',
   NULL,
   'MCN LMS reminder: {{templateName}} is due in {{daysRemaining}} day(s). Submit evidence before {{dueAt}}.',
   NULL, '/practical-assessments?role=trainee', 0, 1, 1, 'migration'),

  (UUID(), 'PRACTICAL_OVERDUE_INAPP_V1', 'PRACTICAL_OVERDUE', 'IN_APP', 'en-IN',
   'Practical assessment overdue',
   '{{templateName}} is overdue by {{overdueDays}} day(s). Submit evidence or contact your coordinator.',
   NULL, '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_OVERDUE_EMAIL_V1', 'PRACTICAL_OVERDUE', 'EMAIL', 'en-IN',
   'Overdue practical assessment: {{templateName}}',
   '{{templateName}} is overdue by {{overdueDays}} day(s). Submit evidence immediately or contact your coordinator.',
   '<p><b>{{templateName}}</b> is overdue by <b>{{overdueDays}} day(s)</b>.</p><p>Submit evidence immediately or contact your coordinator.</p>',
   '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),

  (UUID(), 'PRACTICAL_MODERATION_INAPP_V1', 'PRACTICAL_MODERATION_REQUIRED', 'IN_APP', 'en-IN',
   'Practical assessment moderation required',
   '{{traineeName}} · {{templateName}} requires moderation because of {{reasonCode}}.',
   NULL, '/practical-assessments?role=admin', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_MODERATION_EMAIL_V1', 'PRACTICAL_MODERATION_REQUIRED', 'EMAIL', 'en-IN',
   'Moderation required: {{traineeName}} · {{templateName}}',
   '{{traineeName}} ({{employeeId}}) requires practical-assessment moderation. Reason: {{reasonCode}}. Score variance: {{scoreVariancePct}}%.',
   '<p><b>{{traineeName}}</b> ({{employeeId}}) requires practical-assessment moderation.</p><p>Reason: <b>{{reasonCode}}</b><br>Score variance: {{scoreVariancePct}}%</p>',
   '/practical-assessments?role=admin', 1, 1, 1, 'migration'),

  (UUID(), 'PRACTICAL_RESULT_INAPP_V1', 'PRACTICAL_RESULT', 'IN_APP', 'en-IN',
   'Practical assessment finalized',
   '{{templateName}} result: {{finalResult}} · {{finalPercentage}}%.',
   NULL, '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_RESULT_EMAIL_V1', 'PRACTICAL_RESULT', 'EMAIL', 'en-IN',
   'Practical assessment result: {{templateName}} · {{finalResult}}',
   'Hi {{recipientName}}, your {{templateName}} practical assessment is finalized: {{finalResult}} with {{finalPercentage}}%. Open MCN LMS for evaluator feedback.',
   '<p>Hi <b>{{recipientName}}</b>,</p><p>Your <b>{{templateName}}</b> practical assessment is finalized.</p><p style="font-size:20px"><b>{{finalResult}} · {{finalPercentage}}%</b></p><p>Open MCN LMS for evaluator feedback and development notes.</p>',
   '/practical-assessments?role=trainee', 1, 1, 1, 'migration'),
  (UUID(), 'PRACTICAL_RESULT_SMS_V1', 'PRACTICAL_RESULT', 'SMS', 'en-IN',
   NULL,
   'MCN LMS: {{templateName}} practical result {{finalResult}} · {{finalPercentage}}%. Open LMS for feedback.',
   NULL, '/practical-assessments?role=trainee', 1, 1, 1, 'migration');
